In [1]:
import pandas as pd
import numpy as np
import pyecharts
from pyecharts.charts import Bar
from pyecharts import options as opts

In [2]:
data_path = 'patient_data.csv'
data = pd.read_csv(data_path,  encoding = 'euc-kr')

In [3]:
data.head()

,date,ID,degree,hospital,condition,sex,type,age,country,note,출생년도,나이
0,2020-01-20,1,1차,인천의료원,퇴원,여,중국인 관광객,30대,중국,NaN,NaN,NaN
1,2020-01-24,2,1차,국립중앙의료원,퇴원,남,우한 교민,50대,한국,NaN,NaN,NaN
2,2020-01-26,3,1차,일산명지병원,퇴원,남,우한 교민,50대,한국,NaN,NaN,NaN
3,2020-01-27,4,1차,분당서울대병원,퇴원,남,우한 방문자,50대,한국,NaN,NaN,NaN
4,2020-01-30,5,1차,서울의료원,입원,남,우한 방문자,30대,한국,NaN,NaN,NaN

In [4]:
data = data.fillna("")
data.head()

,date,ID,degree,hospital,condition,sex,type,age,country,note,출생년도,나이
0,2020-01-20,1,1차,인천의료원,퇴원,여,중국인 관광객,30대,중국,,,
1,2020-01-24,2,1차,국립중앙의료원,퇴원,남,우한 교민,50대,한국,,,
2,2020-01-26,3,1차,일산명지병원,퇴원,남,우한 교민,50대,한국,,,
3,2020-01-27,4,1차,분당서울대병원,퇴원,남,우한 방문자,50대,한국,,,
4,2020-01-30,5,1차,서울의료원,입원,남,우한 방문자,30대,한국,,,

In [5]:
age = list(np.sort(data.age.unique()))
age_value = list(data.age.value_counts().sort_index())

In [6]:
age_bar = (
        Bar()
        .add_xaxis(age)
        .add_yaxis("확진자 수(명)", age_value, color="#BDBDBD")
        .set_global_opts(title_opts=opts.TitleOpts(title=""))
        .set_series_opts(label_opts=opts.LabelOpts(position="right", color=["black"]))
        .reversal_axis()
)

In [7]:
age_bar.render('age.html')

'C:\\Users\\ilove\\Desktop\\KU-BIG\\corocoro\\age.html'

In [8]:
age_bar.render_notebook()